{
 "title": "Lysimeter Raw",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "location", "label": "location", "query": "FE1,FE2,FE3,RB1,RB2,GW" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p></p>\n<h1>Flag Check ${location}</h1>"
   }
  },
  {
   "title": "Flags",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flags\")\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> map(fn: (r) => ({r with code: r._value}))\n  |> group(columns: [\"_field\",\"schedule\",\"code\"])\n  |> aggregateWindow(every: 1d, fn: count, column: \"_value\")\n  |> filter(fn: (r) => r._value > 0)\n  |> map(fn: (r) => ({r with code_ng: r.code}))\n  |> map(fn: (r) => ({r with _field_ng: r._field}))\n  |> map(fn: (r) => ({r with schedule_ng: r.schedule}))\n  |> map(fn: (r) => ({r with _time: date.sub(from: r._time, d: 1d)}))\n  //|> map(fn: (r) => ({r with _time: \"${date.year(t:r._time)}-${date.month(t:r._time)}-${date.monthDay(t:r._time)}\"}))\n  |> drop(columns: [\"schedule\",\"_field\",\"code\"])\n  |> map(fn: (r) => ({r with _field: r._field_ng}))\n  |> drop(columns: [\"_field_ng\"])\n\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<h1>Matrix Potential ${location}</h1>"
   }
  },
  {
   "title": "All Lysimeter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_[1-6]_TS1_M_140$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "<p></p>\n<h1>Soil Moisture ${location}</h1>"
   }
  },
  {
   "title": "Lysimeter 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_1_TDR_W_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_2_TDR_W_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_3_TDR_W_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_4_TDR_W_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_5_TDR_W_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_5_TDR_W_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "<p></p>\n<h1>Soil Temperature ${location}</h1>"
   }
  },
  {
   "title": "Lysimeter 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_1_SIS_T_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_2_SIS_T_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_3_SIS_T_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_4_SIS_T_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_5_SIS_T_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter 6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_6_SIS_T_0[1-5]0$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "<p></p>\n<h1>Pumping Rates ${location}</h1>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_[1-6]_PUC_S_NEG/ or r[\"_field\"] =~ /^L_[1-6]_PUC_S_POS/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"H\")\n  |> map(fn: (r) => ({r with _value: if r[\"_field\"] ==  \"L_1_PUC_S_NEG\" then -1.0*r[\"_value\"] else r[\"_value\"]}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 87 },
   "options": {
    "content": "<p></p>\n<h1>Tank Weights ${location}</h1>"
   }
  },
  {
   "title": "Seepage Water",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_[1-6]_WAG_D_000$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"I\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lysimeter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "query": "from(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raw\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^L_[1-6]_WAG_L_000$/)\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\n  |> filter(fn: (r) => r[\"schedule\"] == \"I\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}