{
 "title": "Lysimeter Clean",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p></p>\n<h1>Precipitation</h1>"
   }
  },
  {
   "title": "Monthly Precipitation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"D_PREC\")\n  |> filter(fn: (r) => r[\"component\"] == \"balance\")\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Yearly Precipitation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"D_PREC\")\n  |> filter(fn: (r) => r[\"component\"] == \"balance\")\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 }, "options": { "content": "<p></p>\n<h1>Evporation</h1>" } },
  {
   "title": "Monthly Evaporation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"D_EVAP\")\n  |> filter(fn: (r) => r[\"component\"] == \"balance\")\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Yearly Evaporation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"D_EVAP\")\n  |> filter(fn: (r) => r[\"component\"] == \"balance\")\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 }, "options": { "content": "<p></p>\n<h1>Drainage</h1>" } },
  {
   "title": "Monthly Drainage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"D_DRAIN\")\n  |> filter(fn: (r) => r[\"component\"] == \"balance\")\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Yearly Drainage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"lysimeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"D_DRAIN\")\n  |> filter(fn: (r) => r[\"component\"] == \"balance\")\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\n"
    }
   ]
  }
 ]
}